In [189]:
import pandas as pd
import numpy as np

data = pd.read_csv('train.csv')

In [190]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [191]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [192]:
y = data['Survived']
data.drop('Survived', axis=1, inplace=True)

In [193]:
data.drop(['Cabin', 'PassengerId', 'Name', 'Ticket'], axis=1, inplace=True)

In [194]:
mean_age = np.mean(data['Age'])

In [196]:
data.loc[data['Age'].isnull(), 'Age'] = mean_age

In [123]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
Pclass      891 non-null int64
Sex         891 non-null object
Age         891 non-null float64
SibSp       891 non-null int64
Parch       891 non-null int64
Fare        891 non-null float64
Embarked    889 non-null object
dtypes: float64(2), int64(3), object(2)
memory usage: 48.8+ KB


In [197]:
data['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [198]:
nan_emb = data['Embarked'].isnull()

In [199]:
data.loc[nan_emb, 'Embarked'] = 'S'
data[nan_emb]

Pclass     Sex   Age  SibSp  Parch  Fare Embarked
61        1  female  38.0      0      0  80.0        S
829       1  female  62.0      0      0  80.0        S

In [167]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
PassengerId    891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(4), object(5)
memory usage: 76.6+ KB


In [127]:
data.head()

Pclass     Sex Age SibSp Parch     Fare Embarked
0      3    male  22     1     0     7.25        S
1      1  female  38     1     0  71.2833        C
2      3  female  26     0     0    7.925        S
3      1  female  35     1     0     53.1        S
4      3    male  35     0     0     8.05        S

In [200]:
sex_ohe = pd.get_dummies(data.Sex)

In [201]:
data_s = pd.concat([data, sex_ohe], sort=False, axis=1)

In [202]:
data_s.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked  female  male
0       3    male  22.0      1      0   7.2500        S       0     1
1       1  female  38.0      1      0  71.2833        C       1     0
2       3  female  26.0      0      0   7.9250        S       1     0
3       1  female  35.0      1      0  53.1000        S       1     0
4       3    male  35.0      0      0   8.0500        S       0     1

In [204]:
data_s.drop('Sex', axis=1, inplace=True)

In [205]:
embarked_ohe = pd.get_dummies(data_s.Embarked)
data_s_e = pd.concat([data_s, embarked_ohe], axis=1, sort=False)

In [206]:
data_s_e.drop('Embarked', axis=1, inplace=True)

In [207]:
from sklearn.linear_model import logistic
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

In [212]:
X = data_s_e.values

In [211]:
for i in X_train:
    if type(i) != 'float' or type(i) != 'int':
        print(i)

[3 27.0 0 2 11.1333 1 0 0 0 1]
[2 51.0 0 0 12.525 0 1 0 0 1]
[2 27.0 0 0 13.0 0 1 0 0 1]
[3 30.0 0 0 7.25 0 1 0 0 1]
[3 29.69911764705882 8 2 69.55 0 1 0 0 1]
[3 24.0 0 0 7.4958 0 1 0 0 1]
[2 34.0 0 0 13.0 0 1 0 0 1]
[1 52.0 0 0 30.5 0 1 0 0 1]
[2 0.67 1 1 14.5 0 1 0 0 1]
[1 54.0 1 0 59.4 1 0 1 0 0]
[2 24.0 1 2 65.0 1 0 0 0 1]
[3 24.0 0 0 7.7958 0 1 0 0 1]
[2 34.0 0 0 13.0 1 0 0 0 1]
[3 16.0 1 3 34.375 0 1 0 0 1]
[3 36.0 1 0 15.55 0 1 0 0 1]
[1 45.0 0 0 35.5 0 1 0 0 1]
[3 11.0 5 2 46.9 0 1 0 0 1]
[1 30.0 0 0 31.0 1 0 1 0 0]
[1 29.69911764705882 0 0 31.0 0 1 0 0 1]
[1 61.0 0 0 33.5 0 1 0 0 1]
[1 54.0 1 0 78.2667 1 0 1 0 0]
[3 29.69911764705882 0 0 7.2292 1 0 1 0 0]
[3 38.0 0 0 8.6625 0 1 0 0 1]
[3 11.0 4 2 31.275 1 0 0 0 1]
[3 19.0 0 0 7.8958 0 1 0 0 1]
[2 18.0 0 0 11.5 0 1 0 0 1]
[3 13.0 0 0 7.2292 1 0 1 0 0]
[3 29.69911764705882 0 0 7.75 0 1 0 1 0]
[2 39.0 0 0 26.0 0 1 0 0 1]
[1 48.0 1 0 39.6 1 0 1 0 0]
[3 34.0 0 0 8.05 0 1 0 0 1]
[3 28.5 0 0 16.1 0 1 0 0 1]
[1 38.0 0 0 0.0 0 1 0 0 1]

In [213]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=12)

In [214]:
regr = logistic.LogisticRegression()

In [215]:
regr.fit(X_train, y_train)


/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [216]:
regr.score(X_test, y_test)

0.7821229050279329